trigger:
  - main  # Runs when changes are pushed to the "main" branch

pool:
  name: MyPool  # Use your self-hosted agent pool

steps:
  - script: |
      echo "Installing Python 3.9"
      choco install python --version 3.9 -y
    displayName: 'Install Python'

  - script: |
      python -m venv venv  # Create a virtual environment
      .\venv\Scripts\activate  # Activate the virtual environment (Windows)
      pip install --upgrade pip  # Upgrade pip to the latest version
      pip install robotframework  # Install Robot Framework
      pip install AppiumLibrary  # Install AppiumLibrary for Appium automation
    displayName: 'Install Dependencies'

  - script: |
      .\venv\Scripts\activate  # Ensure the virtual environment is activated (Windows)
      robot --loglevel DEBUG --console width=200 tests/  # Run Robot Framework tests and output results to the console
    displayName: 'Run Robot Framework Tests and Output to Console'

  - script: |
      .\venv\Scripts\activate  # Ensure the virtual environment is activated (Windows)
      echo "Test Run Completed"
      echo "Robot Framework Tests Output:"
      robot --loglevel DEBUG --console width=200 tests/  # Run the test and output directly to the console
    displayName: 'Display Test Output in Azure Logs'
