trigger:
  - main  # Runs when changes are pushed to the "main" branch

pool:
  name: MyPool  # Use your self-hosted agent pool

steps:
  - script: |
      echo "Installing Python 3.9"
      choco install python --version 3.9 -y
    displayName: 'Install Python'

  - script: |
      pytest tests/
    displayName: 'Run Tests'
