trigger:
  - main

pool:
  name: MyPool

steps:
  - script: |
      echo "Installing Python 3.9"
      choco install python --version 3.9 -y
    displayName: 'Install Python'

  - script: |
      python -m venv venv
      .\venv\Scripts\activate
      pip install --upgrade pip
      pip install pytest pytest-azurepipelines robotframework robotframework-appiumlibrary
    displayName: 'Install Dependencies'

  - script: |
      mkdir results
    workingDirectory: $(Build.SourcesDirectory)
    displayName: 'Create Results Directory'

  - script: |
      .\venv\Scripts\activate
      pytest tests/ --junitxml=$(Build.SourcesDirectory)/pytest_results.xml
    displayName: 'Run Python Tests'

  - script: |
      .\venv\Scripts\activate
      robot --outputdir $(Build.SourcesDirectory)/results Tests/
      echo "Checking results directory..."
      dir $(Build.SourcesDirectory)/results
    displayName: 'Run Robot Framework Tests & Verify Output'

  - script: |
      echo "Checking if results directory exists..."
      if not exist "$(Build.SourcesDirectory)/results" mkdir "$(Build.SourcesDirectory)/results"
      echo "Copying results to staging directory..."
      mkdir "$(Build.ArtifactStagingDirectory)/results"
      xcopy /E /I "$(Build.SourcesDirectory)/results" "$(Build.ArtifactStagingDirectory)/results"
    displayName: 'Copy Results to Artifact Staging Directory'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/pytest_results.xml'
      testRunTitle: 'PyTest Results'
      mergeTestResults: true
    condition: succeededOrFailed()
    displayName: 'Publish PyTest Results'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '$(Build.ArtifactStagingDirectory)/results/output.xml'
      testRunTitle: 'Robot Framework Results'
      mergeTestResults: true
    condition: succeededOrFailed()
    displayName: 'Publish Robot Framework Results'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)/results'
      artifactName: 'TestReports'
    condition: succeededOrFailed()
    displayName: 'Publish Robot Framework Reports'
