trigger:
  - main  # Trigger the pipeline on changes to the main branch

pool:
  name: MyPool  # Use your self-hosted agent pool

steps:
  - task: CmdLine@2
    inputs:
      script: |
        echo "Installing Python 3.9 and Robot Framework"
        choco install python --version 3.9 -y
        python -m venv venv  # Create a virtual environment
        .\venv\Scripts\activate  # Activate the virtual environment
        pip install --upgrade pip
        pip install robotframework  # Install Robot Framework
    displayName: 'Install Python and Robot Framework'

  - task: CmdLine@2
    inputs:
      script: |
        echo "Running Robot Framework Tests"
        .\venv\Scripts\activate
        robot --randomize all --loglevel TRACE --outputdir results Tests/
        # Display the results directly in the log
        tail -n 10 results/log.html  # Show the last 10 lines of the log file
    displayName: 'Run Robot Framework Tests and Show Results in Logs'

  - task: CmdLine@2
    inputs:
      script: |
        echo "Parsing the Robot Framework result to display test counts"
        if exist results/output.xml (
          python -c "
import xml.etree.ElementTree as ET
tree = ET.parse('results/output.xml')
root = tree.getroot()

# Extracting test statistics
total_tests = root.find('statistics').find('total').text
passed_tests = root.find('statistics').find('passed').text
failed_tests = root.find('statistics').find('failed').text
skipped_tests = root.find('statistics').find('skipped').text

print(f'Total Tests: {total_tests}')
print(f'Passed Tests: {passed_tests}')
print(f'Failed Tests: {failed_tests}')
print(f'Skipped Tests: {skipped_tests}')
          "
        ) else (
          echo "No output.xml file found."
        )
    displayName: 'Display Test Results Count in Logs'
