trigger:
  - main

pool:
  name: MyPool

steps:
  - script: |
      echo "Installing Python 3.9"
      choco install python --version 3.9 -y
    displayName: 'Install Python'

  - script: |
      python -m venv venv
      .\venv\Scripts\activate
      pip install --upgrade pip
      pip install pytest robotframework robotframework-appiumlibrary
    displayName: 'Install Dependencies'

  - script: |
      mkdir results
    workingDirectory: $(Build.SourcesDirectory)
    displayName: 'Create Results Directory'

  - script: |
      .\venv\Scripts\activate
      pytest tests/ --junitxml=$(Build.SourcesDirectory)/results/pytest_results.xml
    displayName: 'Run PyTest Tests'

  - script: |
      .\venv\Scripts\activate
      robot --outputdir $(Build.SourcesDirectory)/results Tests/
    displayName: 'Run Robot Framework Tests'

  - script: |
      echo "Verifying the test result files..."
      if exist "$(Build.SourcesDirectory)/results/output.xml" (
        echo "Found Robot Framework result file"
      ) else (
        echo "Robot Framework result file not found"
      )
      if exist "$(Build.SourcesDirectory)/results/pytest_results.xml" (
        echo "Found PyTest result file"
      ) else (
        echo "PyTest result file not found"
      )
    displayName: 'Verify Test Result Files'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '$(Build.SourcesDirectory)/results/output.xml'
      testRunTitle: 'Robot Framework Results'
      mergeTestResults: true
    condition: succeededOrFailed()
    displayName: 'Publish Robot Framework Results'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '$(Build.SourcesDirectory)/results/pytest_results.xml'
      testRunTitle: 'PyTest Results'
      mergeTestResults: true
    condition: succeededOrFailed()
    displayName: 'Publish PyTest Results'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)/results'
      artifactName: 'TestReports'
    condition: succeededOrFailed()
    displayName: 'Publish Robot Framework Reports'
