trigger:
  - main  # Runs when changes are pushed to the "main" branch

pool:
  name: MyPool  # Use your self-hosted agent pool

steps:
  - script: |
      echo "Installing Python 3.9"
      choco install python --version 3.9 -y
    displayName: 'Install Python'

  - script: |
      python -m venv venv  # Create a virtual environment
      .\venv\Scripts\activate  # Activate the virtual environment (Windows)
      pip install --upgrade pip  # Upgrade pip to the latest version
      pip install robotframework  # Install Robot Framework
    displayName: 'Install Dependencies'

  - script: |
      .\venv\Scripts\activate  # Ensure the virtual environment is activated (Windows)
      robot --outputdir results tests/  # Run Robot Framework tests and save results to the "results" folder
    displayName: 'Run Robot Framework Tests'

  - script: |
      .\venv\Scripts\activate  # Ensure the virtual environment is activated (Windows)
      robot --outputdir results --loglevel DEBUG tests/  # Run Robot Framework tests with detailed logging
      echo "Test Run Completed"
      echo "Tests Run: $(robot --output results/output.xml --report results/report.html --log results/log.html)"
    displayName: 'Generate Test Report and Logs'
