trigger:
  - main

pool:
  name: MyPool

steps:
  - script: |
      echo "Installing Python 3.x"
      choco install python --version 3.x -y
    displayName: 'Install Python'

  - script: |
      python -m venv venv
      source venv/bin/activate
      pip install -r requirements.txt
    displayName: 'Install Dependencies'

  - script: |
      pytest tests/
    displayName: 'Run Tests'
